photos:
    resource: "@PhotosBundle/Controller/"
    type:     annotation
    prefix:   /

pb_photo:
    resource: "@PBPhotoBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
