<?php

namespace PhotosBundle\Repository;

/**
 * PhotoPathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
}
